version: '3.9'

networks:
  public:
    external: true

volumes:
  traefik_logs:
  traefik_certs:
  traefik_conf:

services:
  traefik:
    image: "traefik:latest"
    command:
      - --entrypoints.http.address=:80
      - --entryPoints.http.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --entrypoints.https.address=:443
      - --entryPoints.https.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
      - --entrypoints.https.http.tls=true
      - --entryPoints.dns-tcp.address=:53
      - --entryPoints.dns-udp.address=:53/udp
      - --entryPoints.ldap.address=:389
      - --entryPoints.ldaps.address=:636
      - --entryPoints.dns-tls.address=:853
      - --entryPoints.ssh.address=:2222
      - --entryPoints.torrent-tcp.address=:51413
      - --entryPoints.torrent-udp.address=:51413/udp
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      - --providers.file.filename=/conf/traefik-dynamic.yml
      - --api
      - --log.level=ERROR
      - --accesslog=false
      - --log.filePath=/logs/traefik.log
      - --log.level=INFO # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accesslog.filepath=/logs/access.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=test@example.com
      - --certificatesresolvers.cloudflare.acme.storage=/etc/certs/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1,1.0.0.1
      - --serversTransport.insecureSkipVerify=true 
    # environment:
      #- "CLOUDFLARE_EMAIL="
      #- "CLOUDFLARE_API_KEY="
    ports:
      - target: 53
        published: 53
        protocol: UDP
        mode: host
      - target: 53
        published: 53
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 389
        published: 389
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 636
        published: 636
        mode: host
      - target: 853
        published: 853
        mode: host
      - target: 2222
        published: 2222
        mode: host
      - target: 51413
        published: 51413
        mode: host
      - target: 51413
        published: 51413
        protocol: UDP
        mode: host
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"

        - "traefik.docker.network=public"
        - "traefik.constraint-label=public"

        - "traefik.http.routers.traefik-https.rule=Host(`traefik.example.com`)"
        - "traefik.http.routers.traefik-https.entrypoints=https"
        - "traefik.http.routers.traefik-https.tls=true"
        - "traefik.http.routers.traefik-https.tls.certresolver=cloudflare"
        - "traefik.http.routers.traefik-https.tls.domains[0].main=example.com"
        - "traefik.http.routers.traefik-https.tls.domains[0].sans=*.example.com"
        - "traefik.http.routers.traefik-https.service=api@internal"
        - "traefik.http.services.public.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "traefik_logs:/etc/certs"
      - "traefik_conf:/conf"
      - "traefik_logs:/logs"
